import { test, expect } from '@playwright/test'
import { accountingCompany, cleanupAccountingCompany, api, choose, DATE, db, expectJournal, expectTrialBalance, payThroughForm } from './accounting-helpers'

test.setTimeout(120_000)
test.use({ actionTimeout: 15_000 })
test.afterEach(async () => { await cleanupAccountingCompany() })
test.afterAll(async () => { await db.$disconnect() })

test('PO form → goods-receipt API → bill form → payment; GR/IR clears without duplicate stock', async ({ page }) => {
  const { orgId, vendor, item } = await accountingCompany(page)
  await page.goto('/ap/pos/new')
  await choose(page, 'Search & select vendor…', vendor.name)
  await page.getByLabel('PO numbering').selectOption('manual')
  await page.getByPlaceholder('e.g. PO-TC-0001').filter({ visible: true }).fill('PO-JOURNEY')
  await page.locator('main input[type="date"]').first().fill(DATE)
  await page.getByPlaceholder('Search SKU or name to add…').filter({ visible: true }).fill(item.name)
  await page.getByText(item.name, { exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByPlaceholder('Description').filter({ visible: true }) })
  await row.locator('input[type="number"]').nth(0).fill('3')
  await row.locator('input[type="number"]').nth(1).fill('1000')
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await page.waitForURL(url => url.pathname === '/ap/pos')
  const po = await db.purchaseOrder.findFirstOrThrow({ where: { organizationId: orgId }, include: { lines: true } })
  expect(po.number).toBe('PO-JOURNEY')
  expect(po.vendorId).toBe(vendor.id)
  expect(po.status).toBe('DRAFT')
  expect(po.lines).toHaveLength(1)
  expect(po.lines[0].itemId).toBe(item.id)
  expect([Number(po.lines[0].quantity), Number(po.lines[0].price), Number(po.lines[0].receivedQty)]).toEqual([3, 1000, 0])
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(0)
  await api(page, `/purchase-orders/${po.id}`, { status: 'APPROVED' }, 'PUT')
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(0)
  const received = await api(page, `/purchase-orders/${po.id}/receive`, {
    lines: [{ purchaseOrderLineId: po.lines[0].id, qtyReceived: 3 }],
  }, 'POST')
  const receiptEntry = await db.journalEntry.findFirstOrThrow({ where: { organizationId: orgId } })
  await expectJournal(orgId, receiptEntry.id, [['1-1300', 3000, 0], ['2150', 0, 3000]])
  expect(Number((await db.purchaseOrderLine.findUniqueOrThrow({ where: { id: po.lines[0].id } })).receivedQty)).toBe(3)
  expect((await db.purchaseOrder.findUniqueOrThrow({ where: { id: po.id } })).status).toBe('CLOSED')

  await page.goto(`/ap/bills/new?billId=${received.billId}`)
  await expect(page.getByPlaceholder('Description').filter({ visible: true })).toHaveValue(item.name)
  await page.getByPlaceholder('e.g. INV/DE/8842').filter({ visible: true }).fill('PO-SUPPLIER-INVOICE')
  await page.getByRole('button', { name: 'Save & schedule payment', exact: true }).click()
  await page.waitForURL(url => url.pathname === '/ap/bills')
  const bill = await db.bill.findUniqueOrThrow({ where: { id: received.billId }, include: { lines: true } })
  await expectJournal(orgId, bill.journalEntryId!, [['2150', 3000, 0], ['2-1000', 0, 3000]])
  expect(Number((await db.purchaseOrderLine.findUniqueOrThrow({ where: { id: po.lines[0].id } })).receivedQty)).toBe(3)
  const stock = await db.inventoryLedgerEntry.findMany({ where: { organizationId: orgId, itemId: item.id } })
  expect(stock).toHaveLength(1)
  expect([Number(stock[0].qtyIn), Number(stock[0].valueChange)]).toEqual([3, 3000])
  await payThroughForm(page, 'ap', vendor.name, bill.number, bill.issueDate.toISOString().slice(0, 10))
  const payment = await db.aPPayment.findFirstOrThrow({ where: { organizationId: orgId } })
  await expectJournal(orgId, payment.journalEntryId!, [['2-1000', 3000, 0], ['1-1000', 0, 3000]])
  expect((await db.bill.findUniqueOrThrow({ where: { id: bill.id } })).status).toBe('PAID')
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(3)
  const report = await api(page, `/reports/gl?type=trial-balance&asOfDate=${bill.issueDate.toISOString().slice(0, 10)}`)
  expect(report.rows.map((r: { accountCode: string; endingDebit: number; endingCredit: number }) =>
    [r.accountCode, r.endingDebit, r.endingCredit])).toEqual([
      ['1-1000', 0, 3000], ['1-1300', 3000, 0], ['2-1000', 0, 0], ['2150', 0, 0],
    ])
})

test('expense bill retry and reload preserve accounts, tax, withholding and charges', async ({ page }) => {
  const { orgId, vendor } = await accountingCompany(page)
  const expense = await db.account.findFirstOrThrow({ where: { organizationId: orgId, code: '5-1100' } })
  const freight = await db.account.findFirstOrThrow({ where: { organizationId: orgId, code: '5-1000' } })
  await page.goto('/ap/bills/new')
  await choose(page, 'Search & select vendor…', vendor.name)
  await page.getByPlaceholder('e.g. INV/DE/8842').filter({ visible: true }).fill('EXPENSE-JOURNEY')
  await page.locator('main input[type="date"]').first().fill(DATE)
  await page.getByPlaceholder('Search SKU or name to add…').filter({ visible: true }).fill('Journey expense')
  await page.getByText('Add “Journey expense” as a custom line').click()
  const row = page.getByRole('row').filter({ has: page.getByPlaceholder('Description').filter({ visible: true }) })
  await row.locator('select').selectOption(expense.id)
  await row.locator('input[type="number"]').nth(0).fill('2')
  await row.locator('input[type="number"]').nth(1).fill('5000')
  await row.locator('input[type="number"]').nth(2).fill('10')
  await page.getByRole('button', { name: 'Additional costs', exact: true }).click()
  await page.getByRole('button', { name: 'Add cost' }).click()
  const chargeRow = page.getByRole('row').filter({ has: page.getByPlaceholder('e.g. Delivery / freight').filter({ visible: true }) })
  await page.getByPlaceholder('e.g. Delivery / freight').filter({ visible: true }).fill('Delivery')
  await chargeRow.locator('select').selectOption(freight.id)
  await chargeRow.locator('input[type="number"]').nth(0).fill('11')
  await chargeRow.locator('input[type="number"]').nth(1).fill('1000')
  await page.getByRole('button', { name: 'Additional info', exact: true }).click()
  await page.getByRole('checkbox', { name: 'With PPN 11%' }).check()
  await page.locator('select').filter({ has: page.locator('option', { hasText: 'No withholding' }) }).selectOption('2')
  await page.getByPlaceholder('Optional notes / PO reference…').filter({ visible: true }).fill('Expense persistence check')

  // Interrupt only the first submission; retry goes to the real server.
  await page.route('**/api/v1/bills', async route => {
    if (route.request().method() === 'POST') {
      await route.abort('failed')
    } else await route.continue()
  })
  // Dismiss while the click is in flight: Playwright waits for an open dialog
  // before resolving click(), so handling it afterwards deadlocks the test.
  const failed = page.waitForEvent('dialog').then(async dialog => {
    expect(dialog.message()).toContain('Failed to save bill')
    await dialog.dismiss()
  })
  await Promise.all([
    failed,
    page.getByRole('button', { name: 'Save draft', exact: true }).click(),
  ])
  await page.unroute('**/api/v1/bills')
  expect(await db.bill.count({ where: { organizationId: orgId } })).toBe(0)
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(0)
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await page.waitForURL(url => url.pathname === '/ap/bills')
  const bill = await db.bill.findFirstOrThrow({ where: { organizationId: orgId }, include: { lines: true, charges: true } })
  expect(bill.status).toBe('DRAFT')
  expect(bill.notes).toBe('Expense persistence check')
  expect([Number(bill.subtotal), Number(bill.taxAmount), Number(bill.withholdingAmount), Number(bill.totalAmount)])
    .toEqual([9000, 1100, 180, 10920])
  expect(bill.lines).toHaveLength(1)
  expect(bill.lines[0].accountId).toBe(expense.id)
  expect(bill.charges).toHaveLength(1)
  expect(bill.charges[0].accountId).toBe(freight.id)
  expect(Number(bill.charges[0].amount)).toBe(1000)
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(0)

  await page.goto(`/ap/bills/new?billId=${bill.id}`)
  await page.reload()
  await expect(page.getByPlaceholder('e.g. INV/DE/8842').filter({ visible: true })).toHaveValue('EXPENSE-JOURNEY')
  await expect(row.locator('select')).toHaveValue(expense.id)
  await expect(row.locator('input[type="number"]').nth(0)).toHaveValue('2')
  await expect(row.locator('input[type="number"]').nth(1)).toHaveValue('5000')
  await expect(row.locator('input[type="number"]').nth(2)).toHaveValue('10')
  await expect(page.getByPlaceholder('Optional notes / PO reference…').filter({ visible: true })).toHaveValue('Expense persistence check')
  await page.getByRole('button', { name: 'Additional costs', exact: true }).click()
  await expect(chargeRow.locator('select')).toHaveValue(freight.id)
  await expect(chargeRow.locator('input[type="number"]').nth(1)).toHaveValue('1000')
  await page.getByRole('button', { name: 'Additional info', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'With PPN 11%' })).toBeChecked()
  await expect(page.locator('select').filter({ has: page.locator('option', { hasText: 'No withholding' }) })).toHaveValue('2')
  await page.getByRole('button', { name: 'Save & schedule payment', exact: true }).click()
  await page.waitForURL(url => url.pathname === '/ap/bills')
  const posted = await db.bill.findUniqueOrThrow({ where: { id: bill.id } })
  await expectJournal(orgId, posted.journalEntryId!, [
    ['5-1100', 9000, 0], ['5-1000', 1000, 0], ['1-1400', 1100, 0], ['2160', 0, 180], ['2-1000', 0, 10920],
  ])
  expect(await db.bill.count({ where: { organizationId: orgId } })).toBe(1)
  expect(await db.inventoryLedgerEntry.count({ where: { organizationId: orgId } })).toBe(0)
  const pl = await api(page, `/reports/gl?type=profit-loss&dateFrom=${DATE}&dateTo=${DATE}`)
  expect(pl.summary).toMatchObject({ totalRevenue: 0, totalExpense: 10000, netIncome: -10000 })

  // Duplicate supplier invoice is rejected atomically, without an extra bill,
  // journal, or stock movement. A different reference can then be saved.
  const orgHeader = { 'x-active-org': orgId }
  const payload = { vendorId: vendor.id, vendorInvoiceNo: 'EXPENSE-JOURNEY', issueDate: DATE, status: 'OPEN',
    lines: [{ description: 'Duplicate expense', accountId: expense.id, quantity: 1, price: 500, lineTotal: 500 }] }
  const duplicate = await page.request.post('http://localhost:3100/api/v1/bills', { headers: orgHeader, data: payload })
  expect(duplicate.status()).toBe(409)
  expect(await db.bill.count({ where: { organizationId: orgId } })).toBe(1)
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(1)
  await api(page, '/bills', { ...payload, vendorInvoiceNo: 'CORRECTED-REFERENCE' }, 'POST')
  expect(await db.bill.count({ where: { organizationId: orgId } })).toBe(2)
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(2)
})

test('purchase bill form → database → inventory/tax/AP journal → payment form → reports', async ({ page }) => {
  const { orgId, vendor, item } = await accountingCompany(page)
  await page.goto('/ap/bills/new')
  await choose(page, 'Search & select vendor…', vendor.name)
  await page.getByPlaceholder('e.g. INV/DE/8842').filter({ visible: true }).fill('PURCHASE-JOURNEY')
  await page.locator('main input[type="date"]').first().fill(DATE)
  await page.getByPlaceholder('Search SKU or name to add…').filter({ visible: true }).fill(item.name)
  await page.getByText(item.name, { exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByPlaceholder('Description').filter({ visible: true }) })
  await row.locator('input[type="number"]').nth(0).fill('3')
  await row.locator('input[type="number"]').nth(1).fill('1000')
  await row.locator('input[type="number"]').nth(2).fill('10')
  await page.getByRole('button', { name: 'Additional info', exact: true }).click()
  await page.getByRole('checkbox', { name: 'With PPN 11%' }).check()
  await page.getByRole('button', { name: 'Save & schedule payment', exact: true }).click()
  await page.waitForURL(url => url.pathname === '/ap/bills')

  const bills = await db.bill.findMany({ where: { organizationId: orgId }, include: { lines: true } })
  expect(bills).toHaveLength(1)
  const bill = bills[0]
  expect(bill.vendorId).toBe(vendor.id)
  expect(bill.vendorInvoiceNo).toBe('PURCHASE-JOURNEY')
  expect(bill.issueDate.toISOString().slice(0, 10)).toBe(DATE)
  expect(bill.status).toBe('OPEN')
  expect([Number(bill.subtotal), Number(bill.taxAmount), Number(bill.totalAmount)]).toEqual([2700, 297, 2997])
  expect(bill.lines).toHaveLength(1)
  expect(bill.lines[0].itemId).toBe(item.id)
  expect([Number(bill.lines[0].quantity), Number(bill.lines[0].price), Number(bill.lines[0].discountPct), Number(bill.lines[0].lineTotal)])
    .toEqual([3, 1000, 10, 2700])
  await expectJournal(orgId, bill.journalEntryId!, [['1-1300', 2700, 0], ['1-1400', 297, 0], ['2-1000', 0, 2997]])
  const stock = await db.inventoryLedgerEntry.findMany({ where: { organizationId: orgId, itemId: item.id } })
  expect(stock).toHaveLength(1)
  expect([Number(stock[0].qtyIn), Number(stock[0].valueChange)]).toEqual([3, 2700])
  await expectTrialBalance(page, [['1-1300', 2700, 0], ['1-1400', 297, 0], ['2-1000', 0, 2997]])

  await payThroughForm(page, 'ap', vendor.name, bill.number)
  const payment = await db.aPPayment.findFirstOrThrow({ where: { organizationId: orgId }, include: { allocations: true } })
  expect(payment.status).toBe('COMPLETED')
  expect(Number(payment.totalAmount)).toBe(2997)
  expect(payment.allocations).toHaveLength(1)
  expect(payment.allocations[0].billId).toBe(bill.id)
  expect(Number(payment.allocations[0].amountApplied)).toBe(2997)
  await expectJournal(orgId, payment.journalEntryId!, [['2-1000', 2997, 0], ['1-1000', 0, 2997]])
  expect((await db.bill.findUniqueOrThrow({ where: { id: bill.id } })).status).toBe('PAID')
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(2)
  await expectTrialBalance(page, [['1-1000', 0, 2997], ['1-1300', 2700, 0], ['1-1400', 297, 0], ['2-1000', 0, 0]])
  const pl = await api(page, `/reports/gl?type=profit-loss&dateFrom=${DATE}&dateTo=${DATE}`)
  expect(pl.summary.netIncome).toBe(0) // Buying stock is not an expense yet.
})

test('invoice draft survives reload → sales/tax/COGS journals → receipt form → reports', async ({ page }) => {
  const { orgId, vendor, customer, item } = await accountingCompany(page)
  // Arrange real purchased stock, not mocked availability or a cached balance.
  await api(page, '/bills', {
    vendorId: vendor.id, vendorInvoiceNo: 'STOCK-FOR-SALE', issueDate: DATE, status: 'OPEN',
    taxable: false, taxRate: 0, lines: [{ itemId: item.id, description: item.name, quantity: 10, price: 1000, lineTotal: 10000 }],
  }, 'POST')
  await page.goto('/ar/invoices/new')
  await choose(page, 'Search & Select Customer...', customer.name)
  await page.locator('input[name="issueDate"]:visible').fill(DATE)
  await page.locator('input[name="dueDate"]:visible').fill('2026-10-15')
  await page.getByPlaceholder('Type to search items or add custom line...').filter({ visible: true }).fill(item.name)
  await page.getByText(item.name, { exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByPlaceholder('Description').filter({ visible: true }) })
  await row.locator('input[type="number"]').nth(0).fill('2')
  await row.locator('input[type="number"]').nth(1).fill('2000')
  await row.locator('input[type="number"]').nth(2).fill('10')
  await page.getByRole('button', { name: 'Logistics & Notes' }).click()
  await page.getByRole('checkbox', { name: 'Apply Tax' }).check()
  await page.getByRole('checkbox', { name: 'Total includes tax' }).uncheck()
  await page.locator('textarea[name="notes"]').fill('Persist these sales details')
  const savedDraft = page.waitForResponse(r => r.url().endsWith('/api/v1/invoices') && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  expect((await savedDraft).ok()).toBeTruthy()
  await expect(page.getByRole('button', { name: 'Save draft', exact: true })).toBeHidden()
  const invoice = await db.salesInvoice.findFirstOrThrow({ where: { organizationId: orgId }, include: { lines: true } })
  expect(invoice.status).toBe('DRAFT')
  expect(invoice.customerId).toBe(customer.id)
  expect(invoice.notes).toBe('Persist these sales details')
  expect(invoice.issueDate.toISOString().slice(0, 10)).toBe(DATE)
  expect(invoice.dueDate!.toISOString().slice(0, 10)).toBe('2026-10-15')
  expect([Number(invoice.subtotal), Number(invoice.taxAmount), Number(invoice.totalAmount)]).toEqual([3600, 396, 3996])
  expect(invoice.lines).toHaveLength(1)
  expect(invoice.lines[0].itemId).toBe(item.id)
  expect([Number(invoice.lines[0].quantity), Number(invoice.lines[0].price), Number(invoice.lines[0].discountPct)])
    .toEqual([2, 2000, 10])
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(1) // Only the stock bill.

  await page.goto(`/ar/invoices/edit?invoiceId=${invoice.id}`)
  await page.reload()
  await expect(page.locator('input[name="issueDate"]:visible')).toHaveValue(DATE)
  await expect(page.locator('input[name="dueDate"]:visible')).toHaveValue('2026-10-15')
  await expect(page.getByPlaceholder('Description').filter({ visible: true })).toHaveValue(item.name)
  await expect(row.locator('input[type="number"]').nth(0)).toHaveValue('2')
  await expect(row.locator('input[type="number"]').nth(1)).toHaveValue('2000')
  await expect(row.locator('input[type="number"]').nth(2)).toHaveValue('10')
  await page.getByRole('button', { name: 'Logistics & Notes' }).click()
  await expect(page.getByRole('checkbox', { name: 'Apply Tax' })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Total includes tax' })).not.toBeChecked()
  await expect(page.locator('textarea[name="notes"]:visible')).toHaveValue('Persist these sales details')
  const approvedInvoice = page.waitForResponse(r => r.url().endsWith(`/api/v1/invoices/${invoice.id}`) && r.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Save & Approve', exact: true }).click()
  const approvedResponse = await approvedInvoice
  expect(approvedResponse.ok(), await approvedResponse.text()).toBeTruthy()
  const postedLines = await db.salesInvoiceLine.findMany({ where: { invoiceId: invoice.id } })
  expect(postedLines).toHaveLength(1)
  expect(postedLines[0].itemId).toBe(item.id)
  await expect(page.getByRole('button', { name: 'Save & Approve', exact: true })).toBeHidden()
  const entries = await db.journalEntry.findMany({ where: { organizationId: orgId, memo: { contains: invoice.number } } })
  expect(entries).toHaveLength(2)
  const sale = entries.find(e => e.memo?.startsWith('Sales recognition:'))!
  const cogs = entries.find(e => e.id !== sale.id)!
  await expectJournal(orgId, sale.id, [['1-1200', 3996, 0], ['4-1000', 0, 3600], ['2-1100', 0, 396]])
  await expectJournal(orgId, cogs.id, [['5-1000', 2000, 0], ['1-1300', 0, 2000]])
  // A repeated status request cannot post the invoice or consume stock again.
  await api(page, `/invoices/${invoice.id}`, { status: 'SENT' }, 'PUT')
  expect(await db.journalEntry.count({ where: { organizationId: orgId } })).toBe(3)
  const movements = await db.inventoryLedgerEntry.findMany({ where: { organizationId: orgId, itemId: item.id } })
  expect(movements.reduce((s, l) => s + Number(l.qtyIn) - Number(l.qtyOut), 0)).toBe(8)
  expect(movements.reduce((s, l) => s + Number(l.valueChange), 0)).toBe(8000)

  // The current AR payment table identifies its rows by invoice ID.
  await payThroughForm(page, 'ar', customer.name, invoice.id)
  const receipt = await db.aRPayment.findFirstOrThrow({ where: { organizationId: orgId }, include: { allocations: true } })
  expect(receipt.status).toBe('COMPLETED')
  expect(receipt.allocations).toHaveLength(1)
  expect(receipt.allocations[0].invoiceId).toBe(invoice.id)
  expect(Number(receipt.allocations[0].amountApplied)).toBe(3996)
  await expectJournal(orgId, receipt.journalEntryId!, [['1-1000', 3996, 0], ['1-1200', 0, 3996]])
  expect((await db.salesInvoice.findUniqueOrThrow({ where: { id: invoice.id } })).status).toBe('PAID')
  await expectTrialBalance(page, [['1-1000', 3996, 0], ['1-1200', 0, 0], ['1-1300', 8000, 0], ['2-1000', 0, 10000], ['2-1100', 0, 396], ['4-1000', 0, 3600], ['5-1000', 2000, 0]])
  const pl = await api(page, `/reports/gl?type=profit-loss&dateFrom=${DATE}&dateTo=${DATE}`)
  expect(pl.summary).toMatchObject({ totalRevenue: 3600, totalExpense: 2000, netIncome: 1600 })
  const bs = await api(page, `/reports/gl?type=balance-sheet&asOfDate=${DATE}`)
  expect(bs.summary).toMatchObject({ totalAssets: 11996, totalLiabilities: 10396, currentEarnings: 1600, totalLiabilitiesAndEquity: 11996 })
})

