// POST /api/v1/stock-adjustments/[id]/void
// Reverses a posted stock adjustment's variance journal entry, unwinds the
// inventory it moved (removes increases, restores decreases), and marks it VOID.
// If the adjustment was generated by a stock count, the void cascades to that
// count (→ VOIDED) so its status + journal stop contradicting the reversed GL.
import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { corsPreflightResponse } from '@/lib/cors';
import { ok, requireOrg, logAudit } from '@/lib/api-utils';
import { withPermission } from '@/lib/authz';
import { voidStockAdjustment } from '@/lib/stock-adjustment-void';
import { voidStockCountForAdjustment } from '@/lib/stock-count-void';

export const runtime = 'nodejs';

export async function OPTIONS() {
  return corsPreflightResponse();
}

export const POST = withPermission({ module: 'INV_ADJ', action: 'delete' }, async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const orgId = requireOrg(req);
  const date = new Date();

  let voidedCountId: string | null = null;
  const adjustment = await prisma.$transaction(async (tx) => {
    await voidStockAdjustment(tx, orgId, id, { date });
    // Cascade: a count-generated adjustment void must also void the owning count
    // (same transaction — never leave the count POSTED against a reversed GL).
    voidedCountId = await voidStockCountForAdjustment(tx, orgId, id);
    return tx.stockAdjustment.findFirst({
      where: { id, organizationId: orgId },
      include: { lines: { include: { item: { select: { id: true, name: true, sku: true } } } } },
    });
  });

  logAudit({ orgId, actorId: req.headers.get('x-user-id'), entityType: 'StockAdjustment', entityId: id, action: 'VOID', payload: null });
  if (voidedCountId) {
    logAudit({ orgId, actorId: req.headers.get('x-user-id'), entityType: 'StockCount', entityId: voidedCountId, action: 'VOID', payload: { via: 'stock-adjustment-void', adjustmentId: id } });
  }
  return ok(adjustment);
});
