import React, { useState, useMemo } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { CheckCircle, Plus, Save, Trash2, AlertCircle } from 'lucide-react';
import FormPage from '../../components/Layout/FormPage';
import Input from '../../components/UI/Input';
import Button from '../../components/UI/Button';
import { useChartOfAccounts, useJournalEntry, useCreateJournalEntry, useUpdateJournalEntry } from '../../hooks/useGL';
import { formatIDR } from '../../utils/formatters';

const PERIODS = [
    { value: '2026-01', label: 'Jan 2026', closed: true  },
    { value: '2026-02', label: 'Feb 2026', closed: false },
    { value: '2026-03', label: 'Mar 2026', closed: false },
    { value: '2026-04', label: 'Apr 2026', closed: false },
];

let _lineId = 1;
const nextId = () => ++_lineId;

const emptyLine = (accountId = '') => ({
    id:          nextId(),
    accountId,
    description: '',
    debit:       '',
    credit:      '',
});

const SelectField = ({ label, name, value, onChange, error, disabled, children }) => (
    <div className="mb-0">
        {label && <label className="block mb-2 text-sm font-medium text-neutral-700">{label}</label>}
        <select
            className={`block w-full px-3 text-base leading-normal text-neutral-900 bg-neutral-0 border rounded-md min-h-10 transition-[border-color,box-shadow] duration-150 focus:border-primary-500 focus:outline-0 focus:shadow-[0_0_0_3px_var(--color-primary-100)] ${error ? 'border-danger-500' : 'border-neutral-300'}`}
            name={name}
            value={value}
            onChange={onChange}
            disabled={disabled}
        >
            {children}
        </select>
        {error && <div className="w-full mt-1 text-xs text-danger-500">{error}</div>}
    </div>
);

const fcBase = "block w-full px-3 text-base leading-normal text-neutral-900 bg-neutral-0 border border-neutral-300 rounded-md min-h-10 transition-[border-color,box-shadow] duration-150 focus:border-primary-500 focus:outline-0 focus:shadow-[0_0_0_3px_var(--color-primary-100)]";

const JournalEntryForm = () => {
    const navigate = useNavigate();
    const location = useLocation();

    // ── API hooks
    const { data: allAccounts = [] } = useChartOfAccounts();
    const postableAccounts = useMemo(
        () => allAccounts.filter((a) => a.isPostable && a.isActive),
        [allAccounts]
    );
    const defaultAccountId = postableAccounts[0]?.id || '';

    const createJE = useCreateJournalEntry();
    const updateJE = useUpdateJournalEntry();

    // Edit/view mode: entryId passed via location.state
    const entryId = location.state?.id || null;
    const isEditMode = Boolean(entryId);
    const { data: existingEntry, isLoading: entryLoading } = useJournalEntry(entryId);

    const [header, setHeader] = useState({
        entryNo: '',   // generated by API; shown read-only in edit mode
        date:    new Date().toISOString().slice(0, 10),
        period:  PERIODS.find((p) => !p.closed)?.value || '',
        memo:    '',
        source:  'Manual',
    });

    const [lines, setLines] = useState([
        emptyLine(defaultAccountId),
        emptyLine(defaultAccountId),
    ]);

    const [errors,       setErrors]       = useState({});
    const [globalErrors, setGlobalErrors] = useState([]);

    // Load existing entry for edit/view mode (from API)
    React.useEffect(() => {
        if (!existingEntry) return;
        setHeader({
            entryNo: existingEntry.entryNo,
            date:    existingEntry.date,
            period:  existingEntry.period || PERIODS.find((p) => !p.closed)?.value || '',
            memo:    existingEntry.memo,
            source:  existingEntry.source || 'Manual',
        });
        if (existingEntry.lines && existingEntry.lines.length >= 2) {
            setLines(existingEntry.lines.map((l) => ({
                id:          nextId(),
                accountId:   l.accountId,
                description: l.description || '',
                debit:       l.debit  ? String(l.debit)  : '',
                credit:      l.credit ? String(l.credit) : '',
            })));
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [existingEntry?.id]);

    const totals = useMemo(() => {
        const debit  = lines.reduce((s, l) => s + (Number(l.debit)  || 0), 0);
        const credit = lines.reduce((s, l) => s + (Number(l.credit) || 0), 0);
        const diff   = Math.abs(debit - credit);
        return { debit, credit, diff, balanced: diff < 0.01 };
    }, [lines]);

    const handleHeaderChange = (e) => {
        const { name, value } = e.target;
        setHeader((prev) => ({ ...prev, [name]: value }));
        setErrors((prev) => ({ ...prev, [name]: null }));
        setGlobalErrors([]);
    };

    const handleLineChange = (id, field, value) => {
        setLines((prev) =>
            prev.map((line) => (line.id === id ? { ...line, [field]: value } : line))
        );
        setGlobalErrors([]);
    };

    const addLine = () => setLines((prev) => [...prev, emptyLine(defaultAccountId)]);

    const removeLine = (id) => {
        if (lines.length <= 2) return;
        setLines((prev) => prev.filter((l) => l.id !== id));
    };

    const handleLineBlur = (id, field, value) => {
        const num = Number(value);
        if (!num || lines.length !== 2) return;
        const other = lines.find((l) => l.id !== id);
        if (!other || other.debit || other.credit) return;
        const autoField = field === 'debit' ? 'credit' : 'debit';
        setLines((prev) =>
            prev.map((l) => l.id === other.id ? { ...l, [autoField]: String(num) } : l)
        );
    };

    const validate = (requireBalanced) => {
        const hErr  = {};
        const gErrs = [];

        if (!header.date)        hErr.date   = 'Date is required.';
        if (!header.period)      hErr.period  = 'Period is required.';
        if (!header.memo.trim()) hErr.memo    = 'Memo / narration is required.';

        const selectedPeriod = PERIODS.find((p) => p.value === header.period);
        if (selectedPeriod?.closed) {
            gErrs.push(`Period "${selectedPeriod.label}" is closed. Please select an open period.`);
        }

        const activeLines = lines.filter((l) => Number(l.debit) > 0 || Number(l.credit) > 0);
        if (activeLines.length < 2) gErrs.push('At least 2 lines with amounts are required.');

        const bothSides = activeLines.filter(
            (l) => Number(l.debit) > 0 && Number(l.credit) > 0
        );
        if (bothSides.length > 0) gErrs.push('A single line cannot have both debit and credit amounts.');

        if (requireBalanced && !totals.balanced) {
            gErrs.push(
                `Entry is not balanced. Debit ${formatIDR(totals.debit)} ≠ Credit ${formatIDR(totals.credit)}. Difference: ${formatIDR(totals.diff)}.`
            );
        }

        setErrors(hErr);
        setGlobalErrors(gErrs);
        return Object.keys(hErr).length === 0 && gErrs.length === 0;
    };

    const isSaving = createJE.isPending || updateJE.isPending;

    const persistEntry = async (status) => {
        try {
            if (isEditMode && entryId) {
                await updateJE.mutateAsync({ id: entryId, header, lines, status });
            } else {
                await createJE.mutateAsync({ header, lines, status });
            }
            navigate('/gl/journals');
        } catch (err) {
            setGlobalErrors([err.message || 'Save failed. Please try again.']);
        }
    };

    const handleSaveDraft = () => { if (validate(false)) { persistEntry('Draft'); } };
    const handlePost      = () => { if (validate(true))  { persistEntry('Posted'); } };

    return (
        <FormPage
            containerClassName=""
            title="New Journal Entry"
            backTo="/gl/journals"
            backLabel="Back to Journal Entries"
            actions={
                <>
                    <Button text="Cancel"     variant="secondary" onClick={() => navigate('/gl/journals')} />
                    <Button text="Save Draft" variant="secondary" icon={<Save size={16} />} onClick={handleSaveDraft} disabled={isSaving} />
                    <Button
                        text="Post Entry"
                        variant="primary"
                        icon={<CheckCircle size={16} />}
                        onClick={handlePost}
                        disabled={!totals.balanced || isSaving}
                    />
                </>
            }
        >

            {globalErrors.length > 0 && (
                <div className="mb-4 bg-danger-50 border border-danger-200 text-danger-700 rounded-md py-3 px-4 text-sm flex gap-2 items-start">
                    <AlertCircle size={16} className="shrink-0 mt-0.5" />
                    <ul className="m-0 pl-4">
                        {globalErrors.map((err, i) => <li key={i} className="mb-1">{err}</li>)}
                    </ul>
                </div>
            )}

            <div className="bg-neutral-0 border border-neutral-200 rounded-lg p-5 mt-4 border-t-3 border-t-primary-500">
                <div className="mb-4 pb-3 border-b border-neutral-100">
                    <span className="text-base font-semibold text-neutral-800">Entry Header</span>
                </div>

                <div className="grid grid-cols-12 gap-4 items-start">
                    <div className="col-span-3">
                        <Input
                            label="Entry No."
                            name="entryNo"
                            value={header.entryNo || (isEditMode && entryLoading ? 'Loading…' : 'Auto-generated')}
                            onChange={() => {}}
                            disabled
                        />
                    </div>
                    <div className="col-span-3">
                        <Input label="Date *" name="date" type="date" value={header.date} onChange={handleHeaderChange} error={errors.date} />
                    </div>
                    <div className="col-span-3">
                        <SelectField label="Accounting Period *" name="period" value={header.period} onChange={handleHeaderChange} error={errors.period}>
                            <option value="">— Select Period —</option>
                            {PERIODS.map((p) => (
                                <option key={p.value} value={p.value} disabled={p.closed}>
                                    {p.label}{p.closed ? ' (Closed)' : ''}
                                </option>
                            ))}
                        </SelectField>
                    </div>
                    <div className="col-span-3">
                        <SelectField label="Entry Type" name="source" value={header.source} onChange={handleHeaderChange}>
                            <option value="Manual">Manual Entry</option>
                            <option value="Adjustment">Adjustment</option>
                            <option value="Accrual">Accrual</option>
                            <option value="Prepayment">Prepayment / Deferral</option>
                            <option value="Depreciation">Depreciation</option>
                            <option value="Closing">Closing Entry</option>
                            <option value="Opening">Opening Balance</option>
                            <option value="Reversal">Reversal</option>
                        </SelectField>
                    </div>
                    <div className="col-span-12">
                        <Input label="Memo / Narration *" name="memo" value={header.memo} onChange={handleHeaderChange} placeholder="Describe the purpose of this entry (appears on GL reports)" error={errors.memo} />
                    </div>
                </div>
            </div>

            <div className="bg-neutral-0 border border-neutral-200 rounded-lg p-5 mt-4">
                <div className="mb-4 pb-3 border-b border-neutral-100">
                    <span className="text-base font-semibold text-neutral-800">Lines</span>
                    <span className="text-neutral-600 text-sm"> — fill Debit or Credit per line, not both</span>
                </div>

                <div className="w-full text-sm">
                    <div className="grid grid-cols-[40px_1fr_1fr_140px_140px_40px] gap-2 py-2 px-3 bg-neutral-100 rounded-t-lg font-semibold text-neutral-600 border-b border-neutral-200">
                        <div>#</div>
                        <div>Account</div>
                        <div>Description</div>
                        <div className="text-right">Debit (IDR)</div>
                        <div className="text-right">Credit (IDR)</div>
                        <div />
                    </div>

                    {lines.map((line, index) => {
                        const hasDebit  = Number(line.debit)  > 0;
                        const hasCredit = Number(line.credit) > 0;
                        return (
                            <div
                                key={line.id}
                                className={`grid grid-cols-[40px_1fr_1fr_140px_140px_40px] gap-2 py-2 px-3 items-center ${index % 2 === 1 ? 'bg-neutral-50' : 'bg-neutral-0'} border-b border-neutral-200`}
                            >
                                <div className="text-neutral-500 text-center font-medium">{index + 1}</div>

                                <div>
                                    <select
                                        className={fcBase}
                                        value={line.accountId}
                                        onChange={(e) => handleLineChange(line.id, 'accountId', e.target.value)}
                                    >
                                        {postableAccounts.map((a) => (
                                            <option key={a.id} value={a.id}>
                                                {a.code} — {a.name}
                                            </option>
                                        ))}
                                    </select>
                                </div>

                                <div>
                                    <input
                                        className={fcBase}
                                        value={line.description}
                                        placeholder="Line memo"
                                        onChange={(e) => handleLineChange(line.id, 'description', e.target.value)}
                                    />
                                </div>

                                <div>
                                    <input
                                        className={`${fcBase} text-right ${hasCredit ? 'opacity-40' : ''}`}
                                        type="number"
                                        min="0"
                                        value={line.debit}
                                        placeholder="—"
                                        disabled={hasCredit}
                                        onChange={(e) => handleLineChange(line.id, 'debit', e.target.value)}
                                        onBlur={(e) => handleLineBlur(line.id, 'debit', e.target.value)}
                                    />
                                </div>

                                <div>
                                    <input
                                        className={`${fcBase} text-right ${hasDebit ? 'opacity-40' : ''}`}
                                        type="number"
                                        min="0"
                                        value={line.credit}
                                        placeholder="—"
                                        disabled={hasDebit}
                                        onChange={(e) => handleLineChange(line.id, 'credit', e.target.value)}
                                        onBlur={(e) => handleLineBlur(line.id, 'credit', e.target.value)}
                                    />
                                </div>

                                <div className="flex justify-center">
                                    <button
                                        type="button"
                                        className="text-neutral-400 bg-none border-none cursor-pointer hover:text-danger-500 disabled:opacity-40 disabled:cursor-not-allowed"
                                        onClick={() => removeLine(line.id)}
                                        disabled={lines.length <= 2}
                                        title="Remove line"
                                    >
                                        <Trash2 size={14} />
                                    </button>
                                </div>
                            </div>
                        );
                    })}
                </div>

                <div className="flex justify-between items-center mt-4">
                    <div className="flex items-center gap-3">
                        <Button text="Add Line" variant="secondary" size="small" icon={<Plus size={14} />} onClick={addLine} />
                        <span className="text-sm text-neutral-500">{lines.length} line{lines.length !== 1 ? 's' : ''}</span>
                    </div>

                    <div className="flex flex-col items-end gap-1">
                        <div className="flex justify-between gap-6">
                            <span className="text-neutral-600">Total Debit</span>
                            <span className="font-semibold">{formatIDR(totals.debit)}</span>
                        </div>
                        <div className="flex justify-between gap-6">
                            <span className="text-neutral-600">Total Credit</span>
                            <span className="font-semibold">{formatIDR(totals.credit)}</span>
                        </div>
                        <div className={`flex items-center gap-1.5 mt-1 ${totals.balanced ? 'text-success-500' : 'text-danger-500'}`}>
                            {totals.balanced ? (
                                <><CheckCircle size={14} /> Balanced</>
                            ) : (
                                <><AlertCircle size={14} /> Off by {formatIDR(totals.diff)}</>
                            )}
                        </div>
                    </div>
                </div>
            </div>

        </FormPage>
    );
};

export default JournalEntryForm;
